TILE_SIZE = 32
CHARACTER_WIDTH = 32
CHARACTER_HEIGHT = 32

CAMERA_SPEED = 100
BACKGROUND_SCROLL_SPEED = 10
PLAYER_WALK_SPEED = 80
PLAYER_JUMP_VELOCITY = -150
GRAVITY = 5
loot1, loot2, loot3, loot4, loot5 = true, true, true, true, true